### ISSUE TITLE
Newbie can't run the code

### ISSUE THREAD

**Issue by mowat27** [adamtornhill/MetricsTreeMap#1]
HI,

I'm not familiar with Processing but I have figured out how to install and start it (on OSX using homebrew).

However, whenever I try to run one of the .pde files I'm getting the same error:

```
No library found for treemap
No library found for treemap
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.
```

Can you show me how to fix this?  I'm happy to update the README if that helps.

Cheers

Adrian

**Comment by adamtornhill** [comment]
Hi @mowat27,

You need to download the treemap library developed by Ben Fry. The library is available [here](http://benfry.com/writing/treemap/). That page also contains the setup instructions.

If you look in you processing IDE, you'll see that you have an `Import Library` option under the `Sketch` menu.

HTH,
Adam

**Comment by mowat27** [comment]
OK, great.  Thanks for the update.

I'm not getting any time to look at this any further at the moment so I'll close the issue and raise a PR with the doc changes when I get a chance
