### ISSUE TITLE
The package "treemap" does not exist. You might be missing a library.

### ISSUE THREAD

**Issue by Bill** [adamtornhill/MetricsTreeMap#2]
I cloned the repo and then downloaded Processing for OS X.

After opening `MetricsTreeMap.pde` in Processing I get that error. It's expecting to find the "treemap" library in a libraries folder in the sketchbook folder.

**Comment by Bill** [comment]
<img width="706" alt="screen shot 2015-11-19 at 4 15 07 pm" src="https://cloud.githubusercontent.com/assets/4002/11288456/0e72f6b6-8ed9-11e5-8deb-6f5ee0eaed0d.png">

**Comment by adamtornhill** [comment]
The visualization uses a third-party library that you need to install. I've described how in issue #1
